AllCops:
  Include:
    - 'lib/**/*'
  Exclude:
    - 'daru.gemspec'
    - 'Rakefile'
    - 'Gemfile'
    - 'Guardfile'
    - '**/*.erb'
    - 'spec/*'
    - 'spec/**/*'
    - 'vendor/**/*'
    - 'benchmarks/*'
    - 'profile/*'
    - 'tmp/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.6
