language:
  ruby

rvm:
  - 2.4
  - 2.5
  - 2.6


script:
  - gem install bundler
  - bundle add yard-junk
  - bundle install
  - bundle exec rspec
  - bundle exec rubocop
  - bundle exec yard-junk

install:
  - gem install rainbow -v '2.2.1'
  - bundle install

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgsl0-dev r-base r-base-dev
  - sudo Rscript -e "install.packages(c('Rserve','irr'),,'http://cran.us.r-project.org')"
  - sudo apt-get install libmagickwand-dev imagemagick
